env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download

builds:
  - id: kubefwd
    main: ./cmd/kubefwd/kubefwd.go
    binary: kubefwd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{.Version}}

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - kubefwd
    dockerfile: Dockerfile
    image_templates:
      - "txn2/kubefwd:latest"
      - "txn2/kubefwd:{{ .Tag }}"
      - "txn2/kubefwd:v{{ .Major }}"
      - "txn2/kubefwd:amd64-{{ .Tag }}"
      - "txn2/kubefwd:amd64-v{{ .Major }}"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/txn2/kubefwd
    description: Kubernetes bulk port forwarding utility.
    maintainer: Craig Johnston https://twitter.com/cjimti
    license: Apache 2.0
    vendor: https://github.com/txn2
    formats:
      - apk
      - deb
      - rpm
    recommends:
      - kubectl

release:
  github:
    owner: txn2
    name: kubefwd
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

brews:
  - name: kubefwd
    tap:
      owner: txn2
      name: homebrew-tap
    commit_author:
      name: Craig Johnston
      email: cj@imti.co
    folder: Formula
    homepage: https://github.com/txn2/kubefwd
    description: "Kubernetes bulk port forwarding utility."
    skip_upload: false
    dependencies:
      - name: kubectl
        type: optional
    test: |-
      kubefwd version