env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download

builds:
  - id: kubefwd
    main: ./cmd/kubefwd/kubefwd.go
    binary: kubefwd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
      - -a
      - -v
    ldflags: -s -w -X main.Version={{.Version}}

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

# dockers:
#   -
#     goos: linux
#     goarch: amd64
#     goarm: ''
#     dockerfile: Dockerfile.alpine
#     ids:
#       - kubefwd
#     image_templates:
#       - "txn2/kubefwd:latest"
#       - "txn2/kubefwd:{{ .Tag }}"
#       - "txn2/kubefwd:v{{ .Major }}"
#       - "txn2/kubefwd:amd64-{{ .Tag }}"
#       - "txn2/kubefwd:amd64-v{{ .Major }}"
#       - "txn2/kubefwd:latest_alpine-3"
#       - "txn2/kubefwd:{{ .Tag }}_alpine-3"
#       - "txn2/kubefwd:v{{ .Major }}_alpine-3"
#       - "txn2/kubefwd:amd64-{{ .Tag }}_alpine-3"
#       - "txn2/kubefwd:amd64-v{{ .Major }}_alpine-3"
#     build_flag_templates:
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"
#   -
#     goos: linux
#     goarch: amd64
#     goarm: ''
#     dockerfile: Dockerfile.ubuntu
#     ids:
#       - kubefwd
#     image_templates:
#       - "txn2/kubefwd:latest_ubuntu-20.04"
#       - "txn2/kubefwd:{{ .Tag }}_ubuntu-20.04"
#       - "txn2/kubefwd:v{{ .Major }}_ubuntu-20.04"
#       - "txn2/kubefwd:amd64-{{ .Tag }}_ubuntu-20.04"
#       - "txn2/kubefwd:amd64-v{{ .Major }}_ubuntu-20.04"
#     build_flag_templates:
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows

        # The format to use for the given GOOS.
        #
        # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, `binary`, and `none`.
        format: zip

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/CodeCoil/kubefwd
    description: Kubernetes bulk port forwarding utility (Fork on CodeCoil).
    maintainer: Luca Piombino
    license: Apache 2.0
    vendor: https://github.com/CodeCoil
    formats:
      - apk
      - deb
      - rpm
    recommends:
      - kubectl

release:
  github:
    owner: CodeCoil
    name: kubefwd
  name_template: "{{.ProjectName}}-v{{.Version}}"

# brews:
#   - name: kubefwd
#     tap:
#       owner: txn2
#       name: homebrew-tap
#     commit_author:
#       name: Craig Johnston
#       email: cj@imti.co
#     folder: Formula
#     homepage: https://github.com/txn2/kubefwd
#     description: "Kubernetes bulk port forwarding utility."
#     skip_upload: false
#     dependencies:
#       - name: kubectl
#         type: optional
#     test: |-
#       kubefwd version
